### ISSUE TITLE
Make library more generic (only dependent on Starlette)

### ISSUE THREAD

**Issue by iffius** [chrisK824/fastapi-gae-logging#1]
First, thank you for figuring this out.  It works great.

I ended up adapting this library to work with [Fasthtml](https://fastht.ml/) which is also based on [Starlette](https://www.starlette.io/). 

Using the `Startlette` app would make this library work seamlessly with `FastAPI`, `Fasthtml`, `Startlette` and possibly any other frameworks based off of `Starlette`.

**Comment by chrisK824** [comment]
Hi @iffius , thanks for pointing this out!

I just released a new version, where I dropped the FastAPI dependency and replaced with just Starlette.

I tried to reflect that a bit in the readme etc, but its too late for the package name hehe, thanks anyway mate!

**Comment by iffius** [comment]
@chrisK824 Thanks!  I just verified everything works well!
